### ISSUE TITLE
DetailList support for complex data type

### ISSUE THREAD

**Issue by AstroNorman** [microsoft/powercat-code-components#8]
<img width="304" alt="complex data type" src="https://user-images.githubusercontent.com/106515086/177233713-e346ab7b-0dc2-46f8-9c4e-0284cce7cdba.PNG">

I am using trying to use the DetailList to list out the data from a sharepoint data source. And I found that there is no way to just access the properties in the collection, liked Requestor.DisplayName, compared to the Data Table control.

**Comment by Ramakrishnan24689** [comment]
Hi @AstroNorman,

Since Person or Group field of SharePoint list/Library returns a Object Type, An additional column needs to be added in the input collection for storing specific property value that are required in the detail list to be displayed.

So, the Items Property for example will look like below.

`AddColumns('<<SharePointSource>>',"RequestorName",Requestor.DisplayName)`

and columns_items property will be referring this new column after it is included in the Data.

`Table(
    {
        ColName: "RequestorName",
        ColDisplayName: "Requestor Name",
        ColWidth: 150
    }
)`

Going forward, please use the below repository for any issues/discussions as it monitored actively.

https://github.com/microsoft/powercat-creator-kit

Thanks.

**Comment by AstroNorman** [comment]
Hello @Ramakrishnan24689 

I try your suggestion

I have added the following to the item property
<img width="395" alt="items" src="https://user-images.githubusercontent.com/106515086/177239310-40707178-feab-4789-ba40-3c2b5e3ed0d1.PNG">

And the following to the columns_item property
<img width="451" alt="column items" src="https://user-images.githubusercontent.com/106515086/177239337-bbd042bd-19f0-40e6-9d06-8da3091cb653.PNG">

But I receive the following error in my DetailList control
<img width="341" alt="error" src="https://user-images.githubusercontent.com/106515086/177239521-a8e81f55-7b77-4133-9e91-3bab42b08945.PNG">

**Comment by daniel-alifano** [comment]
Reopening the whole application generally fixes the error loading control issue

**Comment by AstroNorman** [comment]
<img width="229" alt="column item missing" src="https://user-images.githubusercontent.com/106515086/177241240-5bb798f8-6e5d-4ad4-9414-f41edb15d819.PNG">

After reopening the application, I found that the RequestorName column item is missing.

**Comment by AstroNorman** [comment]
I solve the above problem by adding a field in the DetailList control.
<img width="81" alt="fieldname" src="https://user-images.githubusercontent.com/106515086/177478959-ee86a4c7-457f-4303-ba58-8b474ac7b202.PNG">
